# Generated by Django 4.1.9 on 2023-09-28 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_alter_pet_adoption_date_alter_pet_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Última alteração')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('category', models.PositiveSmallIntegerField(choices=[(None, 'Unknown'), (1, 'Regular event'), (2, 'Health event'), (3, 'Medical appointment'), (4, 'Vaccine')], default=1, verbose_name='Categoria de evento')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('event_date', models.DateField(auto_now=True, null=True, verbose_name='Data do evento')),
                ('event_time', models.TimeField(auto_now=True, null=True, verbose_name='Hora do evento')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.pet', verbose_name='Pet')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ('-created_at',),
            },
        ),
    ]
