# Generated by Django 4.1.9 on 2023-10-03 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeighingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Última alteração')),
                ('weight', models.FloatField(verbose_name='Peso')),
                ('observation', models.TextField(verbose_name='Observação')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.pet', verbose_name='Pet')),
            ],
            options={
                'verbose_name': 'Registro de pesagem',
                'verbose_name_plural': 'Registros de pesagem',
                'ordering': ('id', '-created_at'),
            },
        ),
    ]
