# Generated by Django 4.2.5 on 2023-10-05 03:35

import base_app.models.file
from django.db import migrations, models
import django.db.models.deletion
import project.core_models.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0004_weighingrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Última alteração')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pet',
            name='breed',
            field=models.CharField(blank=True, default='SRD', max_length=255, verbose_name='Raça'),
        ),
        migrations.AddField(
            model_name='pet',
            name='species',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Cachorro'), (2, 'Gato')], null=True, verbose_name='Espécie'),
        ),
        migrations.CreateModel(
            name='EventFile',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_app.file')),
            ],
            options={
                'abstract': False,
            },
            bases=('base_app.file',),
        ),
        migrations.CreateModel(
            name='PetFile',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_app.file')),
            ],
            options={
                'abstract': False,
            },
            bases=('base_app.file',),
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_app.file')),
            ],
            options={
                'abstract': False,
            },
            bases=('base_app.file',),
        ),
        migrations.CreateModel(
            name='EventPicture',
            fields=[
                ('picture_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_app.picture')),
            ],
            options={
                'abstract': False,
            },
            bases=('base_app.picture',),
        ),
        migrations.CreateModel(
            name='PetPicture',
            fields=[
                ('picture_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_app.picture')),
                ('file', models.ImageField(blank=True, null=True, storage=project.core_models.storage_backends.PublicMediaStorage(), upload_to=base_app.models.file.pet_picture_path, verbose_name='Foto de Perfil')),
            ],
            options={
                'abstract': False,
            },
            bases=('base_app.picture',),
        ),
        migrations.CreateModel(
            name='UserProfilePicture',
            fields=[
                ('picture_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_app.picture')),
            ],
            options={
                'abstract': False,
            },
            bases=('base_app.picture',),
        ),
        migrations.AddField(
            model_name='pet',
            name='picture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.petpicture'),
        ),
    ]
