# Generated by Django 4.2.5 on 2023-10-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0006_alter_pet_picture_delete_petpicture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weighingrecord',
            options={'ordering': ('pet', '-created_at'), 'verbose_name': 'Registro de pesagem', 'verbose_name_plural': 'Registros de pesagem'},
        ),
        migrations.AddField(
            model_name='weighingrecord',
            name='date',
            field=models.DateField(null=True, verbose_name='Data do evento'),
        ),
    ]
