# Generated by Django 4.2.5 on 2023-10-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0008_alter_weighingrecord_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(null=True, verbose_name='Data do evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(null=True, verbose_name='Hora do evento'),
        ),
    ]
